clc; 
clear all; 

outer_K = 2.4;
inner_filling_eff = fzero(@(inner_filling_eff) (outer_K - ...
    (((1-inner_filling_eff) * sqrt(2)) / (inner_filling_eff * sqrt(inner_filling_eff)))), .4); % [N/A] Beyvel and Orzechowski, Eq. 5-65

outer_disc_coeff = inner_filling_eff * sqrt(inner_filling_eff / (2 - inner_filling_eff));

fcn = @(outer_S) ((sqrt(1 - outer_disc_coeff^2 * outer_K^2)) ...
        - (outer_S * sqrt(outer_S^2 - outer_disc_coeff^2 * outer_K^2)) ...
        - (outer_disc_coeff^2 * outer_K^2 * log((1 ...
        + sqrt(1 - outer_disc_coeff^2 * outer_K^2)) ...
        / (outer_S + sqrt(outer_S^2 - outer_disc_coeff^2 ...
        * outer_K^2)))) - outer_disc_coeff);



